version: 2.1
orbs:
  node: circleci/node@4.1.0
  aws-cli: circleci/aws-cli@1.3.1
jobs:
  build:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install
      - checkout
      - aws-cli/setup
      - run:
          name: Front-End Install
          command: |
            npm run frontend:install
      - run:
          name: Back-End Install
          command: |
            npm run backend:install
      - run:
          name: Front-End Build
          command: |
            npm run frontend:build
      - run:
          name: Deploy Frontend
          command: aws s3 cp --recursive --acl public-read ./www s3://$FE_BUCKET/
      - run:
          name: Back-End Build
          command: |
            npm run backend:build
      - run:
          name: Deploy Server
          command: |-
            aws s3 cp ./www/app.zip s3://$BE_BUCKET/
            aws elasticbeanstalk create-application-version --application-name $EB_APP --version-label <<pipeline.git.revision>> --source-bundle S3Bucket="$EB_BUCKET",S3Key="app.zip"
            aws elasticbeanstalk update-environment --application-name $EB_APP --environment-name $EB_APP_ENV --version-label <<pipeline.git.revision>>
